CREATE TABLE events (
	id SERIAL PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	description TEXT NOT NULL,
	location VARCHAR(200) NOT NULL,
	event_time TIMESTAMP NOT NULL,
	capacity INT NOT NULL,
	created_by INT REFERENCES users(id) ON DELETE CASCADE,
	status VARCHAR(20) DEFAULT 'ACTIVE',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
